pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import "Singletons"

/** Niri-native window appearance, motion presets, and Sparrow pill spacing. */
SettingsSurface {
    id: root

    backSurface: "settings"
    implicitHeight: content.implicitHeight

    readonly property string preferencesPath: (Quickshell.env("XDG_CONFIG_HOME")
        || (Quickshell.env("HOME") + "/.config")) + "/niri/sparrow/user-appearance.kdl"
    property string preferencesText: ""
    property int gaps: 6
    property int cornerRadius: 12
    property int borderWidth: 2
    property bool shadowsEnabled: true
    property int shadowSoftness: 12
    property string animationPreset: "normal"
    property string note: ""
    property bool seeded: false
    property int pendingRequestId: -1
    property var base: ({})
    property var pillGapControl: null
    property var appGapControl: null
    property var pillOpacityControl: null

    readonly property var animationOptions: [
        { label: "Off", value: "off" },
        { label: "Fast", value: "fast" },
        { label: "Normal", value: "normal" },
        { label: "Smooth", value: "smooth" }
    ]

    rows: {
        var r = [
            { item: gapsRow, kind: "scrub", bump: function (d) { gapsScrub.bump(d); } },
            { item: radiusRow, kind: "scrub", bump: function (d) { radiusScrub.bump(d); } },
            { item: borderRow, kind: "scrub", bump: function (d) { borderScrub.bump(d); } },
            { item: shadowRow, kind: "toggle", get: function () { return root.shadowsEnabled; }, set: function (v) { root.shadowsEnabled = v; root.scheduleWrite(); } }
        ];
        if (root.shadowsEnabled)
            r.push({ item: softnessRow, kind: "scrub", bump: function (d) { softnessScrub.bump(d); } });
        r.push({ item: animationRow, kind: "seg", vals: ["off", "fast", "normal", "smooth"],
            get: function () { return root.animationPreset; }, set: function (v) { root.animationPreset = v; root.scheduleWrite(); } });
        r.push({ item: pillGapRow, kind: "scrub", bump: function (d) { if (root.pillGapControl) root.pillGapControl.bump(d); } });
        r.push({ item: appGapRow, kind: "scrub", bump: function (d) { if (root.appGapControl) root.appGapControl.bump(d); } });
        r.push({ item: pillOpacityRow, kind: "scrub", bump: function (d) { if (root.pillOpacityControl) root.pillOpacityControl.bump(d); } });
        return r;
    }

    function readInt(text, pattern, fallback) {
        var match = text.match(pattern);
        return match ? Number(match[1]) : fallback;
    }

    function seed() {
        root.preferencesText = preferencesFile.text();
        var t = root.preferencesText;
        root.gaps = readInt(t, /^    gaps ([0-9]+)$/m, 6);
        root.borderWidth = readInt(t, /^        width ([0-9]+)$/m, 2);
        root.shadowSoftness = readInt(t, /^        softness ([0-9]+)$/m, 12);
        root.cornerRadius = readInt(t, /^    geometry-corner-radius ([0-9]+)$/m, 12);
        var shadow = t.match(/^        (on|off)$/m);
        root.shadowsEnabled = !shadow || shadow[1] === "on";
        if (/^    off$/m.test(t))
            root.animationPreset = "off";
        else {
            var slowdown = t.match(/^    slowdown (0\.75|1\.0|1\.5)$/m);
            root.animationPreset = !slowdown || slowdown[1] === "1.0" ? "normal"
                : (slowdown[1] === "0.75" ? "fast" : "smooth");
        }
        root.base = {
            gaps: root.gaps,
            cornerRadius: root.cornerRadius,
            borderWidth: root.borderWidth,
            shadowSoftness: root.shadowSoftness,
            topGap: Flags.topGap,
            appGap: Flags.appGap,
            pillOpacity: Flags.pillOpacity
        };
        root.seeded = true;
    }

    function buildPreferences() {
        var slowdown = animationPreset === "fast" ? "0.75"
            : (animationPreset === "smooth" ? "1.5" : "1.0");
        var animationBlock = animationPreset === "off" ? "    off\n" : "    slowdown " + slowdown + "\n";
        var result = "// Generated by Sparrow Look; do not edit.\n"
            + "layout {\n"
            + "    gaps " + gaps + "\n"
            + "    struts {\n"
            + "        left 12\n"
            + "        right 12\n"
            + "        top " + (-gaps) + "\n"
            + "        bottom 12\n"
            + "    }\n"
            + "    border {\n"
            + "        width " + borderWidth + "\n"
            + "    }\n"
            + "    shadow {\n"
            + "        " + (shadowsEnabled ? "on" : "off") + "\n"
            + "        softness " + shadowSoftness + "\n"
            + "    }\n"
            + "}\n"
            + "window-rule {\n"
            + "    geometry-corner-radius " + cornerRadius + "\n"
            + "    clip-to-geometry true\n"
            + "}\n"
            + "animations {\n" + animationBlock + "}\n";
        return result;
    }

    function scheduleWrite() {
        if (root.seeded) {
            root.note = "";
            saveTimer.restart();
        }
    }

    function savePreferences() {
        root.pendingRequestId = Niri.writeManagedFragment("user-appearance", buildPreferences());
    }

    onActiveChanged: {
        if (active) {
            preferencesFile.reload();
            seed();
        } else {
            focusRowItem = null;
            kbIndex = -1;
        }
    }

    Connections {
        target: Niri
        function onManagedFragmentWriteFinished(requestId, status, message, token, timeoutSeconds) {
            if (requestId !== root.pendingRequestId)
                return;
            root.pendingRequestId = -1;
            if (status !== "success") {
                root.note = "Niri did not apply the Look change: " + message;
                preferencesFile.reload();
                root.seed();
            } else {
                root.preferencesText = root.buildPreferences();
            }
        }
    }

    FileView {
        id: preferencesFile
        path: root.preferencesPath
        blockLoading: true
        printErrors: false
    }

    Timer {
        id: saveTimer
        interval: 350
        repeat: false
        onTriggered: root.savePreferences()
    }

    component GroupLabel: Text {
        topPadding: 16 * root.s
        bottomPadding: 6 * root.s
        color: Theme.faint
        font.family: Theme.font
        font.pixelSize: 8.5 * root.s
        font.weight: Font.Bold
        font.capitalization: Font.AllUppercase
        font.letterSpacing: 1.2 * root.s
    }

    component Group: Column {
        id: grp
        property string title: ""
        property bool open: false
        default property alias rows: body.data
        width: parent ? parent.width : 0
        spacing: 0

        Item {
            width: parent.width
            height: label.implicitHeight
            GroupLabel { id: label; text: grp.title }
            GlyphIcon {
                anchors.right: parent.right
                anchors.verticalCenter: label.verticalCenter
                width: 15 * root.s
                height: 15 * root.s
                name: "chevron-down"
                color: Theme.faint
                stroke: 2
                rotation: grp.open ? 0 : -90
                Behavior on rotation { NumberAnimation { duration: Motion.fast; easing.type: Easing.OutCubic } }
            }
            MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: grp.open = !grp.open }
        }

        Item {
            width: parent.width
            height: grp.open ? body.implicitHeight : 0
            clip: true
            Behavior on height { NumberAnimation { duration: Motion.fast; easing.type: Easing.OutCubic } }
            Column { id: body; width: parent.width }
        }
    }

    component FieldRow: Item {
        id: field
        property string label: ""
        property string caption: ""
        property bool collapsed: false
        default property alias control: ctrl.data
        readonly property bool focused: root.focusRowItem === field
        readonly property bool expanded: !field.collapsed && (hover.hovered || field.focused)
        readonly property real rowH: 30 * root.s
        readonly property real capH: 14 * root.s
        width: parent ? parent.width : 0
        height: field.collapsed ? 0 : rowH + (expanded && caption.length > 0 ? capH : 0)
        clip: true
        Behavior on height { NumberAnimation { duration: Motion.fast; easing.type: Easing.OutCubic } }

        HoverHandler { id: hover; onHoveredChanged: if (!field.collapsed) root.reportRowHover(field, hovered) }
        Rectangle {
            anchors.fill: parent
            anchors.topMargin: 3 * root.s
            anchors.bottomMargin: 3 * root.s
            radius: 9 * root.s
            color: (hover.hovered || field.focused) ? Theme.frameBg : "transparent"
            Behavior on color { ColorAnimation { duration: Motion.fast } }
        }
        MouseArea { anchors.fill: parent; cursorShape: Qt.PointingHandCursor; onClicked: root.activateRow(field) }
        Column {
            anchors.left: parent.left
            anchors.leftMargin: 9 * root.s
            anchors.verticalCenter: parent.verticalCenter
            spacing: 2 * root.s
            Text { text: field.label; color: Theme.cream; font.family: Theme.font; font.pixelSize: 12.5 * root.s; font.weight: Font.Medium }
            Text { visible: field.expanded && field.caption.length > 0; text: field.caption; color: Theme.faint; font.family: Theme.font; font.pixelSize: 9 * root.s; font.weight: Font.Medium }
        }
        Item {
            id: ctrl
            anchors.right: parent.right
            anchors.rightMargin: 9 * root.s
            anchors.verticalCenter: parent.verticalCenter
            width: childrenRect.width
            height: childrenRect.height
        }
    }

    Column {
        id: content
        z: 100
        anchors.top: parent.top
        anchors.left: parent.left
        anchors.right: parent.right
        spacing: 0
        height: root.height + root.mBottom * root.s
        clip: true

        SettingsHeader { s: root.s; title: "LOOK"; showBack: true }

        Column {
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.leftMargin: 12 * root.s
            anchors.rightMargin: 12 * root.s
            spacing: 0

            Group { id: windowGroup; title: "Window"; open: true
                FieldRow { id: gapsRow; label: "Gaps"; caption: "Space between tiled columns and windows"
                    ScrubValue { id: gapsScrub; s: root.s; value: root.gaps; openValue: root.base.gaps; from: 0; to: 40; step: 1; unit: "px"
                        onEdited: v => { root.gaps = v; root.scheduleWrite(); } }
                }
                FieldRow { id: radiusRow; label: "Corner radius"; caption: "Rounded window geometry"
                    ScrubValue { id: radiusScrub; s: root.s; value: root.cornerRadius; openValue: root.base.cornerRadius; from: 0; to: 30; step: 1; unit: "px"
                        onEdited: v => { root.cornerRadius = v; root.scheduleWrite(); } }
                }
                FieldRow { id: borderRow; label: "Border width"; caption: "Niri window outline thickness"
                    ScrubValue { id: borderScrub; s: root.s; value: root.borderWidth; openValue: root.base.borderWidth; from: 0; to: 8; step: 1; unit: "px"
                        onEdited: v => { root.borderWidth = v; root.scheduleWrite(); } }
                }
                FieldRow { id: shadowRow; label: "Shadows"; caption: "Show a shadow behind windows"
                    LinkToggle { s: root.s; on: root.shadowsEnabled; onToggled: { root.shadowsEnabled = !root.shadowsEnabled; root.scheduleWrite(); } }
                }
                FieldRow { id: softnessRow; label: "Shadow softness"; caption: "Niri shadow blur softness"; collapsed: !root.shadowsEnabled
                    ScrubValue { id: softnessScrub; s: root.s; value: root.shadowSoftness; openValue: root.base.shadowSoftness; from: 0; to: 50; step: 1
                        onEdited: v => { root.shadowSoftness = v; root.scheduleWrite(); } }
                }
            }

            Group { id: motionGroup; title: "Animations"
                FieldRow { id: animationRow; label: "Motion"; caption: "Niri's global animation speed preset"
                    SettingsSeg { s: root.s; options: root.animationOptions; value: root.animationPreset
                        onPicked: v => { root.animationPreset = v; root.scheduleWrite(); } }
                }
            }

            Group { id: pillGroup; title: "Pill"
                FieldRow { id: pillGapRow; label: "Pill gap"; caption: "Space above the pill"
                    ScrubValue { s: root.s; value: Flags.topGap; openValue: root.base.topGap; from: 0; to: 2; step: 0.1; decimals: 1
                        Component.onCompleted: root.pillGapControl = this
                        onEdited: v => Flags.topGap = v }
                }
                FieldRow { id: appGapRow; label: "App gap"; caption: "Space under the pill"
                    ScrubValue { s: root.s; value: Flags.appGap; openValue: root.base.appGap; from: 0; to: 2; step: 0.1; decimals: 1
                        Component.onCompleted: root.appGapControl = this
                        onEdited: v => Flags.appGap = v }
                }
                FieldRow { id: pillOpacityRow; label: "Pill opacity"; caption: "How see-through the pill sits"
                    ScrubValue { s: root.s; value: Flags.pillOpacity; openValue: root.base.pillOpacity; from: 0.55; to: 1; step: 0.05; decimals: 2
                        Component.onCompleted: root.pillOpacityControl = this
                        onEdited: v => Flags.pillOpacity = v }
                }
            }

            Text {
                width: parent.width
                topPadding: 8 * root.s
                visible: root.note.length > 0
                text: root.note
                color: Theme.subtle
                font.family: Theme.font
                font.pixelSize: 10 * root.s
                font.weight: Font.Medium
                wrapMode: Text.WordWrap
            }
            Item { width: 1; height: 10 * root.s }
        }
    }
}
