[Icon Theme]
Name=Sparrow
Comment=Wallpaper-colored folders with cohesive Papirus sidebar icons
Inherits=Adwaita,hicolor
Directories=16x16/actions,16x16/devices,16x16/places,scalable/mimetypes,scalable/places,symbolic/places

[16x16/actions]
Size=16
Type=Fixed
Context=Actions

[16x16/devices]
Size=16
Type=Fixed
Context=Devices

[16x16/places]
Size=16
Type=Fixed
Context=Places

[scalable/mimetypes]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=MimeTypes

[scalable/places]
Size=48
Type=Scalable
MinSize=16
MaxSize=512
Context=Places

[symbolic/places]
Size=16
Type=Scalable
MinSize=16
MaxSize=512
Context=Places
