#!/usr/bin/env python3
"""Integration tests for the managed-fragment transaction helper.

These tests use temporary config/state trees and the installed Niri validator.
They never edit the user's active Niri configuration or send reload IPC to it.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import tempfile
import threading
import unittest
from concurrent.futures import ThreadPoolExecutor


SCRIPT = Path(__file__).with_name("niri-config-transaction.py")
SPEC = importlib.util.spec_from_file_location("niri_config_transaction", SCRIPT)
assert SPEC and SPEC.loader
TRANSACTION = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(TRANSACTION)


def harmless_fragment(color: str) -> str:
    return (
        "// Generated by Sparrow wallpaper palette; do not edit.\n"
        "layout {\n"
        "    border {\n"
        f'        active-color "{color}"\n'
        '        inactive-color "#334455"\n'
        "    }\n"
        "}\n"
    )


class TransactionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory(prefix="sparrow-niri-transaction-test-")
        self.base = Path(self.temp.name)
        self.config_root = self.base / "config" / "niri"
        (self.config_root / "sparrow").mkdir(parents=True)
        (self.config_root / "includes").mkdir()
        (self.config_root / "config.kdl").write_text(
            'include "includes/first.kdl"\nprefer-no-csd\n', encoding="utf-8"
        )
        (self.config_root / "includes" / "first.kdl").write_text(
            'include "second.kdl"\ninclude "../sparrow/generated-colors.kdl"\n', encoding="utf-8"
        )
        (self.config_root / "includes" / "second.kdl").write_text(
            "input {\n    keyboard {\n        numlock\n    }\n}\n", encoding="utf-8"
        )
        self.target = self.config_root / "sparrow" / "generated-colors.kdl"
        self.original = harmless_fragment("#102030")
        self.target.write_text(self.original, encoding="utf-8")
        self.state_root = self.base / "state" / "sparrow-shell"
        self.reload_count = 0
        self.fail_next_reload = False
        self.runner = self.run_niri

    def tearDown(self) -> None:
        self.temp.cleanup()

    def run_niri(self, args, **kwargs):
        if args[1:4] == ["msg", "action", "load-config-file"]:
            self.reload_count += 1
            if self.fail_next_reload:
                self.fail_next_reload = False
                return subprocess.CompletedProcess(args, 1, "", "simulated reload failure")
        return subprocess.run(args, **kwargs)

    def transaction(self, runner=None):
        return TRANSACTION.ConfigTransaction(
            self.config_root / "config.kdl",
            self.state_root,
            command_runner=runner or self.runner,
        )

    def validate_active_fixture(self) -> None:
        result = subprocess.run(
            ["niri", "validate", "-c", str(self.config_root / "config.kdl")],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr or result.stdout)

    def test_valid_candidate_commits_backs_up_and_reloads(self):
        candidate = harmless_fragment("#aabbcc")
        result = self.transaction().transact("generated-colors", candidate)
        self.assertEqual(result["status"], "success", result)
        self.assertTrue(result["changed"])
        self.assertEqual(self.target.read_text(encoding="utf-8"), candidate)
        self.assertEqual(self.reload_count, 1)
        backup = Path(result["backupPath"])
        self.assertEqual((backup / self.target.name).read_text(encoding="utf-8"), self.original)
        metadata = json.loads((backup / "manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(metadata["fragmentId"], "generated-colors")
        self.assertEqual(metadata["previousSha256"], __import__("hashlib").sha256(self.original.encode()).hexdigest())
        self.validate_active_fixture()

    def test_syntax_failure_does_not_touch_active_or_reload(self):
        before = self.target.read_bytes()
        digest = __import__("hashlib").sha256(before).hexdigest()
        malformed = (
            "// Generated by Sparrow wallpaper palette; do not edit.\n"
            "layout {\n    border {\n"
            '        active-color "#aabbcc"\n'
            '        inactive-color "#334455"\n'
        )
        result = self.transaction().transact("generated-colors", malformed)
        self.assertEqual(result["status"], "validation_failed", result)
        self.assertEqual(__import__("hashlib").sha256(self.target.read_bytes()).hexdigest(), digest)
        self.assertEqual(self.reload_count, 0)
        self.validate_active_fixture()
        staging = self.state_root / "niri-config-transactions" / "staging"
        self.assertEqual(list(staging.iterdir()), [])

    def test_semantic_failure_does_not_touch_active_or_reload(self):
        before = self.target.read_bytes()
        invalid_value = harmless_fragment("not-a-valid-color")
        result = self.transaction().transact("generated-colors", invalid_value)
        self.assertEqual(result["status"], "validation_failed", result)
        self.assertEqual(self.target.read_bytes(), before)
        self.assertEqual(self.reload_count, 0)
        self.validate_active_fixture()

    def test_nested_relative_includes_are_preserved(self):
        result = self.transaction().transact("generated-colors", harmless_fragment("#abcdef"))
        self.assertEqual(result["status"], "success", result)
        self.assertTrue((self.config_root / "includes" / "second.kdl").is_file())
        self.validate_active_fixture()

    def test_reload_failure_restores_previous_fragment_and_reload(self):
        self.fail_next_reload = True
        result = self.transaction().transact("generated-colors", harmless_fragment("#abcdef"))
        self.assertEqual(result["status"], "reload_failed", result)
        self.assertTrue(result["rollbackSucceeded"], result)
        self.assertEqual(self.target.read_text(encoding="utf-8"), self.original)
        self.assertEqual(self.reload_count, 2)
        self.assertFalse((self.state_root / "niri-config-transactions" / "pending-transaction.json").exists())
        self.validate_active_fixture()

    def test_interrupted_transaction_is_recovered_before_next_request(self):
        def crash_on_reload(args, **kwargs):
            if args[1:4] == ["msg", "action", "load-config-file"]:
                raise KeyboardInterrupt("simulated helper crash")
            return subprocess.run(args, **kwargs)

        with self.assertRaises(KeyboardInterrupt):
            self.transaction(runner=crash_on_reload).transact(
                "generated-colors", harmless_fragment("#abcdef")
            )
        self.assertNotEqual(self.target.read_text(encoding="utf-8"), self.original)
        self.assertTrue((self.state_root / "niri-config-transactions" / "pending-transaction.json").exists())

        result = self.transaction().transact("generated-colors", self.original)
        self.assertEqual(result["status"], "success", result)
        self.assertEqual(self.target.read_text(encoding="utf-8"), self.original)
        self.assertFalse((self.state_root / "niri-config-transactions" / "pending-transaction.json").exists())
        self.validate_active_fixture()

    def test_concurrent_transactions_serialize(self):
        barrier = threading.Barrier(2)

        def update(color):
            barrier.wait()
            return self.transaction().transact("generated-colors", harmless_fragment(color))

        with ThreadPoolExecutor(max_workers=2) as pool:
            results = list(pool.map(update, ["#aa0000", "#0000aa"]))
        self.assertEqual([r["status"] for r in results], ["success", "success"])
        self.assertIn(self.target.read_text(encoding="utf-8"), [harmless_fragment("#aa0000"), harmless_fragment("#0000aa")])
        self.assertEqual(self.reload_count, 2)
        backups = [p for p in (self.state_root / "backups").iterdir() if p.is_dir()]
        self.assertEqual(len(backups), 2)

    def test_unknown_fragment_id_cannot_select_a_path(self):
        before = self.target.read_bytes()
        result = self.transaction().transact("../config.kdl", "prefer-no-csd\n")
        self.assertEqual(result["status"], "invalid_fragment")
        self.assertEqual(self.target.read_bytes(), before)
        self.assertEqual(self.reload_count, 0)

    def test_retention_keeps_only_twenty_transaction_backups(self):
        backup_root = self.state_root / "backups"
        backup_root.mkdir(parents=True)
        for number in range(25):
            directory = backup_root / f"{TRANSACTION.BACKUP_PREFIX}20260101T0000{number:02d}Z"
            directory.mkdir()
            (directory / "manifest.json").write_text(json.dumps({"schemaVersion": 1}))
        TRANSACTION._prune_backups(backup_root)
        remaining = [p for p in backup_root.iterdir() if p.is_dir()]
        self.assertEqual(len(remaining), 20)


if __name__ == "__main__":
    unittest.main(verbosity=2)
