#!/usr/bin/env python3
"""Integration tests for the managed-fragment transaction helper.

These tests use temporary config/state trees and the installed Niri validator.
They never edit the user's active Niri configuration or send reload IPC to it.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import tempfile
import threading
import unittest
from concurrent.futures import ThreadPoolExecutor


SCRIPT = Path(__file__).with_name("niri-config-transaction.py")
SPEC = importlib.util.spec_from_file_location("niri_config_transaction", SCRIPT)
assert SPEC and SPEC.loader
TRANSACTION = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(TRANSACTION)

INFO_SCRIPT = Path(__file__).with_name("input-system-info.py")
INFO_SPEC = importlib.util.spec_from_file_location("input_system_info", INFO_SCRIPT)
assert INFO_SPEC and INFO_SPEC.loader
INPUT_INFO = importlib.util.module_from_spec(INFO_SPEC)
INFO_SPEC.loader.exec_module(INPUT_INFO)


def harmless_fragment(color: str) -> str:
    return (
        "// Generated by Sparrow wallpaper palette; do not edit.\n"
        "layout {\n"
        "    border {\n"
        f'        active-color "{color}"\n'
        '        inactive-color "#334455"\n'
        "    }\n"
        "}\n"
    )


class TransactionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory(prefix="sparrow-niri-transaction-test-")
        self.base = Path(self.temp.name)
        self.config_root = self.base / "config" / "niri"
        (self.config_root / "sparrow").mkdir(parents=True)
        (self.config_root / "includes").mkdir()
        (self.config_root / "config.kdl").write_text(
            'include "includes/first.kdl"\nprefer-no-csd\n', encoding="utf-8"
        )
        (self.config_root / "includes" / "first.kdl").write_text(
            'include "second.kdl"\ninclude "../sparrow/generated-colors.kdl"\n'
            'include optional=true "../sparrow/user-appearance.kdl"\n'
            'include optional=true "../sparrow/display-outputs.kdl"\n'
            'include "../sparrow/binds.kdl"\n'
            'include optional=true "../sparrow/user-binds.kdl"\n'
            'include optional=true "../sparrow/display-binds.kdl"\n'
            'include "../sparrow/input.kdl"\n', encoding="utf-8"
        )
        (self.config_root / "includes" / "second.kdl").write_text(
            "input {\n    keyboard {\n        numlock\n    }\n}\n", encoding="utf-8"
        )
        self.target = self.config_root / "sparrow" / "generated-colors.kdl"
        self.original = harmless_fragment("#102030")
        self.target.write_text(self.original, encoding="utf-8")
        self.output_target = self.config_root / "sparrow" / "display-outputs.kdl"
        self.output_original = "// Generated by Sparrow Display settings; do not edit.\n"
        self.output_target.write_text(self.output_original, encoding="utf-8")
        self.bind_target = self.config_root / "sparrow" / "display-binds.kdl"
        self.bind_target.write_text(
            '// Generated by Sparrow from the current Niri output arrangement.\n'
            'binds {\n    Super+F1 hotkey-overlay-title="Focus display 1" { focus-monitor "eDP-1"; }\n}\n',
            encoding="utf-8",
        )
        shutil.copyfile(Path(__file__).parents[3] / "niri" / "sparrow" / "binds.kdl",
                        self.config_root / "sparrow" / "binds.kdl")
        (self.config_root / "sparrow" / "input.kdl").write_text(
            'include optional=true "user-input.kdl"\n', encoding="utf-8"
        )
        self.state_root = self.base / "state" / "sparrow-shell"
        self.reload_count = 0
        self.fail_next_reload = False
        self.scheduled_tokens = []
        self.runner = self.run_niri

    def tearDown(self) -> None:
        self.temp.cleanup()

    def test_xkb_layout_database_parser_provides_names_and_codes(self):
        layouts = INPUT_INFO.parse_layouts(
            "! model\n pc105 Generic 105-key PC\n! layout\n us English (US)\n si Slovenian\n! variant\n"
        )
        self.assertEqual(layouts, [
            {"code": "us", "label": "English (US)"},
            {"code": "si", "label": "Slovenian"},
        ])

    def test_udev_device_grouping_deduplicates_touchpad_mouse_interface(self):
        properties = {
            "/dev/input/event0": "ID_PATH_TAG=platform-i8042-serio-0\nID_INPUT_KEYBOARD=1\n",
            "/dev/input/event1": "ID_PATH_TAG=pci-0000-input-touch\nID_INPUT_TOUCHPAD=1\n",
            "/dev/input/event2": "ID_PATH_TAG=pci-0000-input-touch\nID_INPUT_MOUSE=1\n",
            "/dev/input/event3": "ID_PATH_TAG=usb-0000-mouse\nID_INPUT_MOUSE=1\n",
            "/dev/input/event4": "ID_PATH_TAG=usb-wacom\nID_INPUT_TABLET=1\n",
        }

        def fake_runner(args, **kwargs):
            return subprocess.CompletedProcess(args, 0, properties[args[-1]], "")

        devices = INPUT_INFO.discover_devices([Path(path) for path in properties], runner=fake_runner)
        self.assertEqual(devices, {
            "keyboard": True, "touchpad": True, "mouse": True,
            "tablet": True, "touchscreen": False,
        })

    def run_niri(self, args, **kwargs):
        if args[1:4] == ["msg", "action", "load-config-file"]:
            self.reload_count += 1
            if self.fail_next_reload:
                self.fail_next_reload = False
                return subprocess.CompletedProcess(args, 1, "", "simulated reload failure")
            return subprocess.CompletedProcess(args, 0, "", "")
        return subprocess.run(args, **kwargs)

    def transaction(self, runner=None, scheduler=None):
        return TRANSACTION.ConfigTransaction(
            self.config_root / "config.kdl",
            self.state_root,
            command_runner=runner or self.runner,
            rollback_scheduler=scheduler or self.scheduled_tokens.append,
        )

    def validate_active_fixture(self) -> None:
        result = subprocess.run(
            ["niri", "validate", "-c", str(self.config_root / "config.kdl")],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr or result.stdout)

    def test_valid_candidate_commits_backs_up_and_reloads(self):
        candidate = harmless_fragment("#aabbcc")
        result = self.transaction().transact("generated-colors", candidate)
        self.assertEqual(result["status"], "success", result)
        self.assertTrue(result["changed"])
        self.assertEqual(self.target.read_text(encoding="utf-8"), candidate)
        self.assertEqual(self.reload_count, 1)
        backup = Path(result["backupPath"])
        self.assertEqual((backup / self.target.name).read_text(encoding="utf-8"), self.original)
        metadata = json.loads((backup / "manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(metadata["fragmentId"], "generated-colors")
        self.assertEqual(metadata["previousSha256"], __import__("hashlib").sha256(self.original.encode()).hexdigest())
        self.validate_active_fixture()

    def test_user_appearance_fragment_is_restricted_and_transactional(self):
        candidate = (
            "// Generated by Sparrow Look; do not edit.\n"
            "layout {\n"
            "    gaps 8\n"
            "    struts {\n"
            "        left 8\n"
            "        right 8\n"
            "        top -8\n"
            "        bottom 8\n"
            "    }\n"
            "    border {\n"
            "        width 2\n"
            "    }\n"
            "    shadow {\n"
            "        on\n"
            "        softness 12\n"
            "    }\n"
            "}\n"
            "window-rule {\n"
            "    geometry-corner-radius 12\n"
            "    clip-to-geometry true\n"
            "}\n"
            "animations {\n"
            "    slowdown 1.0\n"
            "}\n"
        )
        result = self.transaction().transact("user-appearance", candidate)
        self.assertEqual(result["status"], "success", result)
        target = self.config_root / "sparrow" / "user-appearance.kdl"
        self.assertEqual(target.read_text(encoding="utf-8"), candidate)
        self.assertEqual(self.reload_count, 1)
        self.validate_active_fixture()

        for slowdown in ("0.75", "1.0", "1.5"):
            variant = candidate.replace("slowdown 1.0", "slowdown " + slowdown)
            self.assertTrue(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-appearance", variant))
        for gaps in (0, 1, 20, 40):
            variant = (candidate.replace("gaps 8", f"gaps {gaps}")
                       .replace("left 8", f"left {gaps}")
                       .replace("right 8", f"right {gaps}")
                       .replace("top -8", f"top {-gaps}")
                       .replace("bottom 8", f"bottom {gaps}"))
            self.assertTrue(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-appearance", variant))
        for strut in ("left 8", "right 8", "bottom 8"):
            mismatched_strut = candidate.replace(strut, strut.split()[0] + " 12")
            self.assertFalse(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-appearance", mismatched_strut))
        off_variant = candidate.replace("slowdown 1.0", "off")
        self.assertTrue(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-appearance", off_variant))
        off_result = self.transaction().transact("user-appearance", off_variant)
        self.assertEqual(off_result["status"], "success", off_result)
        self.validate_active_fixture()

        unsafe = candidate + (
            "layer-rule {\n"
            '    match namespace="^pill$"\n'
            "    background-effect {\n"
            "        blur true\n"
            "    }\n"
            "}\n"
        )
        self.assertFalse(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-appearance", unsafe))
        out_of_range = (candidate.replace("    gaps 8", "    gaps 80")
                        .replace("left 8", "left 80")
                        .replace("right 8", "right 80")
                        .replace("top -8", "top -80")
                        .replace("bottom 8", "bottom 80"))
        self.assertFalse(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-appearance", out_of_range))
        extra_directive = candidate.replace("        left 8", "        left 0")
        self.assertFalse(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-appearance", extra_directive))

    def test_user_input_fragment_accepts_managed_classes_and_rejects_injection(self):
        candidate = (
            "// Generated by Sparrow Input; do not edit.\n"
            "input {\n"
            "    keyboard {\n"
            '        xkb {\n            layout "si"\n        }\n'
            "        numlock\n        repeat-rate 25\n        repeat-delay 600\n"
            "    }\n"
            "    touchpad {\n        tap\n        natural-scroll\n        dwt\n"
            '        accel-speed -0.2\n        accel-profile "adaptive"\n'
            "    }\n"
            "    mouse {\n        natural-scroll\n        left-handed\n"
            '        accel-speed 0.1\n        accel-profile "flat"\n'
            "    }\n"
            "    touch {\n        map-to-output \"eDP-1\"\n    }\n"
            "    tablet {\n        map-to-focused-output\n    }\n"
            "    focus-follows-mouse\n"
            "}\n"
        )
        result = self.transaction().transact("user-input", candidate)
        self.assertEqual(result["status"], "success", result)
        self.assertEqual((self.config_root / "sparrow" / "user-input.kdl").read_text(encoding="utf-8"), candidate)
        self.validate_active_fixture()
        self.fail_next_reload = True
        changed = candidate.replace('layout "si"', 'layout "de"')
        result = self.transaction().transact("user-input", changed)
        self.assertEqual(result["status"], "reload_failed", result)
        self.assertTrue(result["rollbackSucceeded"], result)
        self.assertEqual((self.config_root / "sparrow" / "user-input.kdl").read_text(encoding="utf-8"), candidate)

        for invalid in (
            candidate + 'spawn "kitty"\n',
            candidate.replace('layout "si"', 'layout "../../tmp"'),
            candidate.replace('accel-speed -0.2', 'accel-speed 3'),
            candidate.replace('repeat-rate 25', 'repeat-rate 0'),
            candidate.replace('map-to-focused-output', 'map-to-focused-output\n        map-to-output "eDP-1"'),
            candidate.replace('        natural-scroll\n', '        tap\n        natural-scroll\n', 1),
            candidate.replace('focus-follows-mouse', 'focus-follows-mouse\n    layer-rule {\n'),
        ):
            self.assertFalse(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-input", invalid), invalid)

    def test_user_input_requires_complete_class_blocks_without_duplicate_properties(self):
        base = "// Generated by Sparrow Input; do not edit.\ninput {\n    keyboard {\n    }\n}\n"
        seed = Path(__file__).parents[3] / "niri/defaults/user-input.kdl"
        self.assertTrue(TRANSACTION._safe_user_input(seed.read_text()))
        self.assertTrue(TRANSACTION._safe_user_input(base))
        self.assertFalse(TRANSACTION._safe_user_input(base.replace("    keyboard {\n", "    keyboard {\n        numlock\n        numlock\n")))
        self.assertFalse(TRANSACTION._safe_user_input(base.replace("    keyboard {\n", "    keyboard {\n        keymap \"us\"\n")))

    def test_user_binds_accept_only_curated_chord_overrides_and_stage_complete_config(self):
        candidate = json.dumps({"kitty": "Super+Y", "overview": "Super+Shift+O"})
        self.assertTrue(TRANSACTION.ConfigTransaction._safe_fragment_payload("user-binds", candidate))
        result = self.transaction().transact("user-binds", candidate)
        self.assertEqual(result["status"], "success", result)
        target = self.config_root / "sparrow" / "user-binds.kdl"
        written = target.read_text(encoding="utf-8")
        self.assertIn("// override: kitty = Super+Y", written)
        self.assertIn('Super+Y hotkey-overlay-title="Open Kitty" { spawn "kitty"; }', written)
        self.assertIn('Super+T { spawn "true"; }', written)
        self.assertIn("// override: overview = Super+Shift+O", written)
        self.assertEqual(self.reload_count, 1)
        self.validate_active_fixture()

    def test_user_binds_reject_default_display_and_duplicate_chords_without_reload(self):
        for payload in (
            '{"kitty":"Super+E"}',
            '{"kitty":"Super+F1"}',
            '{"kitty":"Super+Y","thunar":"Super+Y"}',
            '{"kitty":"Super+Y","unknown":"Super+U"}',
            '{"kitty":"Super+Y { spawn \\\"bad\\\"; }"}',
        ):
            result = self.transaction().transact("user-binds", payload)
            self.assertEqual(result["status"], "invalid_content", (payload, result))
        self.assertEqual(self.reload_count, 0)
        self.assertFalse((self.config_root / "sparrow" / "user-binds.kdl").exists())

    def test_user_binds_reset_all_replaces_fragment_with_empty_bind_block(self):
        self.transaction().transact("user-binds", '{"kitty":"Super+Y"}')
        result = self.transaction().transact("user-binds", "{}")
        self.assertEqual(result["status"], "success", result)
        self.assertEqual(
            (self.config_root / "sparrow" / "user-binds.kdl").read_text(encoding="utf-8"),
            "// Generated by Sparrow Keybinds; do not edit.\nbinds {\n}\n",
        )
        self.validate_active_fixture()

    def test_user_binds_reset_one_restores_its_default_without_dropping_other_overrides(self):
        result = self.transaction().transact(
            "user-binds", '{"kitty":"Super+Y","firefox":"Super+Alt+F"}'
        )
        self.assertEqual(result["status"], "success", result)
        result = self.transaction().transact("user-binds", '{"firefox":"Super+Alt+F"}')
        self.assertEqual(result["status"], "success", result)
        written = (self.config_root / "sparrow" / "user-binds.kdl").read_text(encoding="utf-8")
        self.assertNotIn("override: kitty", written)
        self.assertNotIn('Super+T { spawn "true"; }', written)
        self.assertIn("// override: firefox = Super+Alt+F", written)
        self.assertIn('Super+F { spawn "true"; }', written)
        self.validate_active_fixture()

    def test_user_binds_reload_failure_restores_previous_overrides(self):
        original = self.transaction().transact("user-binds", '{"kitty":"Super+Y"}')
        self.assertEqual(original["status"], "success", original)
        target = self.config_root / "sparrow" / "user-binds.kdl"
        original_text = target.read_text(encoding="utf-8")
        self.fail_next_reload = True
        result = self.transaction().transact("user-binds", '{"kitty":"Super+U"}')
        self.assertEqual(result["status"], "reload_failed", result)
        self.assertTrue(result["rollbackSucceeded"], result)
        self.assertEqual(target.read_text(encoding="utf-8"), original_text)
        self.validate_active_fixture()

    def test_syntax_failure_does_not_touch_active_or_reload(self):
        before = self.target.read_bytes()
        digest = __import__("hashlib").sha256(before).hexdigest()
        malformed = (
            "// Generated by Sparrow wallpaper palette; do not edit.\n"
            "layout {\n    border {\n"
            '        active-color "#aabbcc"\n'
            '        inactive-color "#334455"\n'
        )
        result = self.transaction().transact("generated-colors", malformed)
        self.assertEqual(result["status"], "validation_failed", result)
        self.assertEqual(__import__("hashlib").sha256(self.target.read_bytes()).hexdigest(), digest)
        self.assertEqual(self.reload_count, 0)
        self.validate_active_fixture()
        staging = self.state_root / "niri-config-transactions" / "staging"
        self.assertEqual(list(staging.iterdir()), [])

    def test_generated_colors_accepts_border_and_recent_window_highlight_only(self):
        colors = (
            "// Generated by Sparrow wallpaper palette; do not edit.\n"
            "layout {\n    border {\n"
            '        active-color "#aabbcc"\n'
            '        inactive-color "#334455"\n'
            "    }\n}\nrecent-windows {\n    highlight {\n"
            '        active-color "#aabbcc"\n'
            '        urgent-color "#dd2233"\n'
            "    }\n}\n"
        )
        self.assertTrue(TRANSACTION.ConfigTransaction._safe_fragment_payload("generated-colors", colors))
        self.assertFalse(TRANSACTION.ConfigTransaction._safe_fragment_payload(
            "generated-colors", colors.replace('urgent-color "#dd2233"', 'spawn "kitty"')))
        result = self.transaction().transact("generated-colors", colors)
        self.assertEqual(result["status"], "success", result)
        self.validate_active_fixture()

    def test_semantic_failure_does_not_touch_active_or_reload(self):
        before = self.target.read_bytes()
        invalid_value = harmless_fragment("not-a-valid-color")
        result = self.transaction().transact("generated-colors", invalid_value)
        self.assertEqual(result["status"], "validation_failed", result)
        self.assertEqual(self.target.read_bytes(), before)
        self.assertEqual(self.reload_count, 0)
        self.validate_active_fixture()

    def test_nested_relative_includes_are_preserved(self):
        result = self.transaction().transact("generated-colors", harmless_fragment("#abcdef"))
        self.assertEqual(result["status"], "success", result)
        self.assertTrue((self.config_root / "includes" / "second.kdl").is_file())
        self.validate_active_fixture()

    def test_reload_failure_restores_previous_fragment_and_reload(self):
        self.fail_next_reload = True
        result = self.transaction().transact("generated-colors", harmless_fragment("#abcdef"))
        self.assertEqual(result["status"], "reload_failed", result)
        self.assertTrue(result["rollbackSucceeded"], result)
        self.assertEqual(self.target.read_text(encoding="utf-8"), self.original)
        self.assertEqual(self.reload_count, 2)
        self.assertFalse((self.state_root / "niri-config-transactions" / "pending-transaction.json").exists())
        self.validate_active_fixture()

    def test_interrupted_transaction_is_recovered_before_next_request(self):
        def crash_on_reload(args, **kwargs):
            if args[1:4] == ["msg", "action", "load-config-file"]:
                raise KeyboardInterrupt("simulated helper crash")
            return subprocess.run(args, **kwargs)

        with self.assertRaises(KeyboardInterrupt):
            self.transaction(runner=crash_on_reload).transact(
                "generated-colors", harmless_fragment("#abcdef")
            )
        self.assertNotEqual(self.target.read_text(encoding="utf-8"), self.original)
        self.assertTrue((self.state_root / "niri-config-transactions" / "pending-transaction.json").exists())

        result = self.transaction().transact("generated-colors", self.original)
        self.assertEqual(result["status"], "success", result)
        self.assertEqual(self.target.read_text(encoding="utf-8"), self.original)
        self.assertFalse((self.state_root / "niri-config-transactions" / "pending-transaction.json").exists())
        self.validate_active_fixture()

    def test_concurrent_transactions_serialize(self):
        barrier = threading.Barrier(2)

        def update(color):
            barrier.wait()
            return self.transaction().transact("generated-colors", harmless_fragment(color))

        with ThreadPoolExecutor(max_workers=2) as pool:
            results = list(pool.map(update, ["#aa0000", "#0000aa"]))
        self.assertEqual([r["status"] for r in results], ["success", "success"])
        self.assertIn(self.target.read_text(encoding="utf-8"), [harmless_fragment("#aa0000"), harmless_fragment("#0000aa")])
        self.assertEqual(self.reload_count, 2)
        backups = [p for p in (self.state_root / "backups").iterdir() if p.is_dir()]
        self.assertEqual(len(backups), 2)

    def test_unknown_fragment_id_cannot_select_a_path(self):
        before = self.target.read_bytes()
        result = self.transaction().transact("../config.kdl", "prefer-no-csd\n")
        self.assertEqual(result["status"], "invalid_fragment")
        self.assertEqual(self.target.read_bytes(), before)
        self.assertEqual(self.reload_count, 0)

    def test_display_fragments_accept_only_restricted_generated_syntax(self):
        output = (
            "// Generated by Sparrow Display settings; do not edit.\n"
            'output "Example Panel Example-1 SERIAL" {\n'
            '    mode "2560x1440@240.002"\n'
            "    scale 1.25\n"
            '    transform "normal"\n'
            "    focus-at-startup\n"
            "    position x=0 y=0\n"
            "}\n"
        )
        result = self.transaction().transact("display-outputs", output)
        self.assertEqual(result["status"], "success", result)
        self.assertEqual(self.output_target.read_text(encoding="utf-8"), output)
        duplicate_focus = output + (
            'output "Second Panel Example-2 SERIAL" {\n'
            '    mode "1920x1080@60.000"\n'
            "    scale 1\n"
            '    transform "normal"\n'
            "    focus-at-startup\n"
            "    position x=2560 y=0\n"
            "}\n"
        )
        self.assertFalse(TRANSACTION._safe_display_outputs(duplicate_focus))

        binds = (
            "// Generated by Sparrow from the current Niri output arrangement.\n"
            "binds {\n"
            '    // sparrow-monitor-number "Example Panel Example-1 SERIAL" 1\n'
            '    Super+F1 hotkey-overlay-title="Focus display 1" { focus-monitor "DP-3"; }\n'
            '    Super+Shift+F1 hotkey-overlay-title="Move focused window to display 1" { move-window-to-monitor "DP-3"; }\n'
            "}\n"
        )
        result = self.transaction().transact("display-binds", binds)
        self.assertEqual(result["status"], "success", result)
        self.assertEqual(self.bind_target.read_text(encoding="utf-8"), binds)
        duplicate_number = binds.replace(
            '    // sparrow-monitor-number "Example Panel Example-1 SERIAL" 1\n',
            '    // sparrow-monitor-number "Example Panel Example-1 SERIAL" 1\n'
            '    // sparrow-monitor-number "Second Panel Example-2 SERIAL" 1\n',
        )
        self.assertFalse(TRANSACTION._safe_display_binds(duplicate_number))

        before = self.output_target.read_bytes()
        unsafe = output.replace('    transform "normal"', '    off\n    spawn "kitty"')
        result = self.transaction().transact("display-outputs", unsafe)
        self.assertEqual(result["status"], "invalid_content", result)
        self.assertEqual(self.output_target.read_bytes(), before)

    def test_display_preview_requires_confirmation_and_can_be_rolled_back(self):
        candidate = (
            "// Generated by Sparrow Display settings; do not edit.\n"
            'output "Example Panel Example-1 SERIAL" {\n'
            '    mode "2560x1440@240.002"\n'
            "    scale 1\n"
            '    transform "normal"\n'
            "    position x=0 y=0\n"
            "}\n"
        )
        transaction = self.transaction()
        result = transaction.transact("display-outputs", candidate, confirm=True)
        self.assertEqual(result["status"], "confirmation_pending", result)
        self.assertEqual(result["timeoutSeconds"], TRANSACTION.DISPLAY_CONFIRM_SECONDS)
        self.assertEqual(self.scheduled_tokens, [result["confirmationToken"]])
        self.assertEqual(self.output_target.read_text(encoding="utf-8"), candidate)

        blocked = transaction.transact("display-binds", "// Generated by Sparrow from the current Niri output arrangement.\nbinds {\n}\n")
        self.assertEqual(blocked["status"], "confirmation_pending", blocked)
        self.assertEqual(self.reload_count, 1)

        rolled_back = transaction.resolve_confirmation(result["confirmationToken"], rollback=True)
        self.assertEqual(rolled_back["status"], "rolled_back", rolled_back)
        self.assertEqual(self.output_target.read_text(encoding="utf-8"), self.output_original)
        self.assertEqual(self.reload_count, 2)
        duplicate_rollback = transaction.resolve_confirmation(result["confirmationToken"], rollback=True)
        self.assertEqual(duplicate_rollback["status"], "already_resolved", duplicate_rollback)
        self.assertEqual(self.reload_count, 2)

    def test_display_preview_confirmation_keeps_active_fragment(self):
        candidate = (
            "// Generated by Sparrow Display settings; do not edit.\n"
            'output "Example Panel Example-1 SERIAL" {\n'
            '    mode "1920x1080@60.000"\n'
            "    scale 1\n"
            '    transform "normal"\n'
            "    position x=0 y=0\n"
            "}\n"
        )
        result = self.transaction().transact("display-outputs", candidate, confirm=True)
        confirmed = self.transaction().resolve_confirmation(result["confirmationToken"], rollback=False)
        self.assertEqual(confirmed["status"], "confirmed", confirmed)
        self.assertEqual(self.output_target.read_text(encoding="utf-8"), candidate)
        self.assertFalse((self.state_root / "niri-config-transactions" / "pending-transaction.json").exists())

    def test_expired_display_confirmation_rolls_back_instead_of_keeping(self):
        candidate = (
            "// Generated by Sparrow Display settings; do not edit.\n"
            'output "Example Panel Example-1 SERIAL" {\n'
            '    mode "1920x1080@60.000"\n'
            "    scale 1\n"
            '    transform "normal"\n'
            "    position x=0 y=0\n"
            "}\n"
        )
        transaction = self.transaction()
        result = transaction.transact("display-outputs", candidate, confirm=True)
        journal = self.state_root / "niri-config-transactions" / "pending-transaction.json"
        state = json.loads(journal.read_text(encoding="utf-8"))
        state["expiresAt"] = 0
        journal.write_text(json.dumps(state), encoding="utf-8")
        expired = transaction.resolve_confirmation(result["confirmationToken"], rollback=False)
        self.assertEqual(expired["status"], "rolled_back", expired)
        self.assertEqual(self.output_target.read_text(encoding="utf-8"), self.output_original)

    def test_retention_keeps_only_twenty_transaction_backups(self):
        backup_root = self.state_root / "backups"
        backup_root.mkdir(parents=True)
        for number in range(25):
            directory = backup_root / f"{TRANSACTION.BACKUP_PREFIX}20260101T0000{number:02d}Z"
            directory.mkdir()
            (directory / "manifest.json").write_text(json.dumps({"schemaVersion": 1}))
        TRANSACTION._prune_backups(backup_root)
        remaining = [p for p in backup_root.iterdir() if p.is_dir()]
        self.assertEqual(len(remaining), 20)


if __name__ == "__main__":
    unittest.main(verbosity=2)
