#!/usr/bin/env python3
"""Exercise the Sparrow role dispatcher without launching desktop apps."""

import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest


SCRIPT = Path(__file__).resolve().parents[3] / "bin/sparrow-launch-app"


class AppLauncherTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="sparrow-app-launcher-test-")
        self.root = Path(self.temp.name)
        self.config = self.root / "config"
        (self.config / "niri/sparrow").mkdir(parents=True)
        self.capture = self.root / "argv.json"
        fake_bin = self.root / "bin"
        fake_bin.mkdir()
        stub = fake_bin / "gtk-launch"
        stub.write_text(
            "#!/usr/bin/env python3\n"
            "import json, os, sys\n"
            "Path = __import__('pathlib').Path\n"
            "Path(os.environ['CAPTURE']).write_text(json.dumps(sys.argv[1:]))\n"
        )
        stub.chmod(0o755)
        self.env = dict(os.environ, HOME=str(self.root), XDG_CONFIG_HOME=str(self.config),
                        PATH=str(fake_bin) + os.pathsep + os.environ.get("PATH", ""),
                        CAPTURE=str(self.capture))

    def tearDown(self):
        self.temp.cleanup()

    def run_launcher(self, *args):
        return subprocess.run([str(SCRIPT), *args], env=self.env, text=True, capture_output=True)

    def test_roles_use_canonical_fresh_defaults(self):
        for role, expected in (("browser", "firefox"), ("terminal", "kitty"), ("file-manager", "sparrow-files")):
            result = self.run_launcher("role", role)
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(json.loads(self.capture.read_text()), [expected])

    def test_selected_role_reads_managed_fragment_and_preserves_desktop_entry(self):
        (self.config / "niri/sparrow/user-binds.kdl").write_text(
            "// Generated by Sparrow Keybinds; do not edit.\n"
            "// app: browser = org.mozilla.firefox\n"
            "binds {\n}\n"
        )
        result = self.run_launcher("role", "browser")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(json.loads(self.capture.read_text()), ["org.mozilla.firefox"])
        result = self.run_launcher("desktop", "sparrow-files")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(json.loads(self.capture.read_text()), ["sparrow-files"])

    def test_invalid_role_or_desktop_id_is_rejected(self):
        self.assertEqual(self.run_launcher("role", "arbitrary").returncode, 2)
        self.assertEqual(self.run_launcher("desktop", "../../etc/passwd").returncode, 2)


if __name__ == "__main__":
    unittest.main()
