#!/usr/bin/env python3
"""Generate Sparrow's Ricelin-derived palette and Niri border color fragment."""
import colorsys
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageStat

HOME = Path.home()
CACHE = Path(os.environ.get("XDG_CACHE_HOME", HOME / ".cache")) / "sparrow-shell"
def tint(h, s, l):
    r, g, b = colorsys.hls_to_rgb(h % 1, max(0, min(1, l)), max(0, min(1, s)))
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))


def analyze(path):
    with Image.open(path) as source:
        im = source.convert("RGB")
        im.thumbnail((200, 200))
        colors = im.quantize(colors=48, method=Image.Quantize.FASTOCTREE).convert("RGB")
        hist = colors.getcolors(40000) or []
        total = sum(n for n, _ in hist)
        mean_l = sum(n * colorsys.rgb_to_hls(*(c / 255 for c in rgb))[1]
                     for n, rgb in hist) / max(total, 1)
        buckets = {}
        chroma = 0
        for count, rgb in hist:
            h, light, sat = colorsys.rgb_to_hls(*(c / 255 for c in rgb))
            if sat < .15 or light < .05 or light > .92:
                continue
            chroma += count
            bucket = int(h * 360) // 30 % 12
            slot = buckets.setdefault(bucket, [0.0, None])
            slot[0] += count * sat
            score = count * sat * (1 if .12 < light < .55 else .4)
            if slot[1] is None or score > slot[1][0]:
                slot[1] = (score, h, sat)
    if not buckets or chroma < .08 * total:
        return .09, 0.0, mean_l, False
    winner = max(buckets.values(), key=lambda v: v[0])[1]
    return winner[1], winner[2], mean_l, True


def atomic_write(path, data):
    if path.is_file() and path.read_text() == data:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)
    return True


def terminal_colors(surfaces):
    """Derive Kitty colors from this same Matugen palette; never sample again."""
    background = surfaces["surface_container_lowest"]
    foreground = surfaces["on_surface"]
    # Use Matugen's contrast-aware semantic roles directly. In particular,
    # Fish's default command color is ANSI blue (color4); a fixed hue here
    # made command text stay blue regardless of the wallpaper.
    semantic = {
        "red": surfaces["error"],
        "green": surfaces["tertiary"],
        "yellow": surfaces["secondary"],
        "blue": surfaces["primary"],
        "magenta": surfaces["tertiary"],
        "cyan": surfaces["secondary"],
    }
    normal = semantic
    bright = semantic
    return {
        "background": background,
        "foreground": foreground,
        "cursor": surfaces["primary"],
        "cursor_text": surfaces["on_primary"],
        "selection_background": surfaces["primary_container"],
        "selection_foreground": surfaces["on_primary_container"],
        "url_color": surfaces["primary"],
        "tab_bar_background": background,
        "active_tab_background": surfaces["primary_container"],
        "active_tab_foreground": surfaces["on_primary_container"],
        "inactive_tab_background": surfaces["surface_container"],
        "inactive_tab_foreground": surfaces["on_surface_variant"],
        "ansi": [
            background, normal["red"], normal["green"], normal["yellow"],
            normal["blue"], normal["magenta"], normal["cyan"], foreground,
            surfaces["outline_variant"], bright["red"], bright["green"],
            bright["yellow"], bright["blue"], bright["magenta"],
            bright["cyan"], surfaces["bright"],
        ],
        # The desktop Starship prompt intentionally uses these extended
        # xterm indices for its pill segments. Override their default greys
        # with equivalent Matugen roles so the copied prompt stays wallpaper-
        # themed on Sparrow as well.
        "extended": {
            235: foreground,
            240: foreground,
            243: surfaces["primary"],
            244: normal["red"],
            245: surfaces["outline_variant"],
            248: surfaces["surface_container"],
            249: normal["red"],
            250: surfaces["surface_container_high"],
            251: normal["magenta"],
            252: surfaces["surface_container_highest"],
            253: normal["blue"],
            254: surfaces["primary_container"],
            255: surfaces["surface_container_highest"],
        },
    }


def render_kitty(palette):
    lines = [
        "# Generated by Sparrow wallpaper palette; do not edit.",
        f"background {palette['background']}",
        f"foreground {palette['foreground']}",
        f"cursor {palette['cursor']}",
        f"cursor_text_color {palette['cursor_text']}",
        f"selection_background {palette['selection_background']}",
        f"selection_foreground {palette['selection_foreground']}",
        f"url_color {palette['url_color']}",
        f"tab_bar_background {palette['tab_bar_background']}",
        f"active_tab_background {palette['active_tab_background']}",
        f"active_tab_foreground {palette['active_tab_foreground']}",
        f"inactive_tab_background {palette['inactive_tab_background']}",
        f"inactive_tab_foreground {palette['inactive_tab_foreground']}",
    ]
    lines.extend(f"color{index} {color}" for index, color in enumerate(palette["ansi"]))
    lines.extend(f"color{index} {color}" for index, color in palette["extended"].items())
    return "\n".join(lines) + "\n"


def render_sparrow_gtk(palette):
    """Apply Matugen roles to adw-gtk3's named palette, preserving its states."""
    data_home = Path(os.environ.get("XDG_DATA_HOME", HOME / ".local/share"))
    candidates = (
        data_home / "themes/adw-gtk3/gtk-3.0/gtk-dark.css",
        Path("/usr/share/themes/adw-gtk3/gtk-3.0/gtk-dark.css"),
    )
    source = next((path for path in candidates if path.is_file()), None)
    if source is None:
        raise FileNotFoundError(
            "adw-gtk3 is missing; install Arch package adw-gtk-theme or the upstream user theme"
        )

    stylesheet = source.read_text()
    colors = {
        "blue_1": palette["primary"],
        "blue_2": palette["primary"],
        "blue_3": palette["primary"],
        "blue_4": palette["primary_container"],
        "blue_5": palette["primary_container"],
        "green_1": palette["tertiary"],
        "green_2": palette["tertiary"],
        "green_3": palette["tertiary"],
        "green_4": palette["tertiary_container"],
        "green_5": palette["tertiary_container"],
        "yellow_1": palette["secondary"],
        "yellow_2": palette["secondary"],
        "yellow_3": palette["secondary"],
        "yellow_4": palette["secondary_container"],
        "yellow_5": palette["secondary_container"],
        "orange_1": palette["secondary"],
        "orange_2": palette["secondary"],
        "orange_3": palette["secondary"],
        "orange_4": palette["secondary_container"],
        "orange_5": palette["secondary_container"],
        "red_1": palette["error"],
        "red_2": palette["error"],
        "red_3": palette["error"],
        "red_4": palette["error"],
        "red_5": palette["on_error"],
        "purple_1": palette["primary"],
        "purple_2": palette["primary"],
        "purple_3": palette["primary"],
        "purple_4": palette["primary_container"],
        "purple_5": palette["primary_container"],
        "brown_1": palette["tertiary"],
        "brown_2": palette["tertiary"],
        "brown_3": palette["tertiary"],
        "brown_4": palette["tertiary_container"],
        "brown_5": palette["tertiary_container"],
        "light_1": palette["on_surface"],
        "light_2": palette["on_surface"],
        "light_3": palette["on_surface_variant"],
        "light_4": palette["on_surface_variant"],
        "light_5": palette["outline"],
        "dark_1": palette["surface_container_highest"],
        "dark_2": palette["surface_container_high"],
        "dark_3": palette["surface_container"],
        "dark_4": palette["surface_container_low"],
        "dark_5": palette["background"],
        "accent_bg_color": palette["primary"],
        "accent_fg_color": palette["on_primary"],
        "destructive_bg_color": palette["error"],
        "destructive_fg_color": palette["on_error"],
        "success_bg_color": palette["tertiary_container"],
        "success_fg_color": palette["on_tertiary_container"],
        "warning_bg_color": palette["secondary_container"],
        "warning_fg_color": palette["on_secondary_container"],
        "error_bg_color": palette["error"],
        "error_fg_color": palette["on_error"],
        "window_bg_color": palette["background"],
        "window_fg_color": palette["on_background"],
        "view_bg_color": palette["surface_container_lowest"],
        "view_fg_color": palette["on_surface"],
        "headerbar_bg_color": palette["surface_container_low"],
        "headerbar_fg_color": palette["on_surface"],
        "headerbar_border_color": palette["outline_variant"],
        "headerbar_backdrop_color": palette["surface_container"],
        "sidebar_bg_color": palette["surface_container_low"],
        "sidebar_fg_color": palette["on_surface"],
        "sidebar_backdrop_color": palette["surface_container"],
        "sidebar_border_color": palette["outline_variant"],
        "card_bg_color": palette["surface_container"],
        "card_fg_color": palette["on_surface"],
        "dialog_bg_color": palette["surface_container_high"],
        "dialog_fg_color": palette["on_surface"],
        "popover_bg_color": palette["surface_container_high"],
        "popover_fg_color": palette["on_surface"],
        "thumbnail_bg_color": palette["surface_container"],
        "thumbnail_fg_color": palette["on_surface"],
        "panel_bg_color": palette["surface_container"],
        "panel_fg_color": palette["on_surface"],
    }
    for name, color in colors.items():
        pattern = re.compile(rf"(@define-color\s+{re.escape(name)}\s+)[^;]+;")
        stylesheet, count = pattern.subn(rf"\g<1>{color};", stylesheet, count=1)
        if count != 1:
            raise ValueError(f"adw-gtk3 stylesheet lacks expected color token: {name}")

    header = (
        "/* Generated by Sparrow from upstream adw-gtk3 GTK3 CSS (LGPL-2.1).\n"
        f" * Source: {source}\n"
        " * Matugen roles replace its named palette; upstream widget/state rules remain intact. */\n"
    )
    return header + stylesheet


def render_folder_icon(palette):
    """Create Sparrow's simple wallpaper-accented folder icon."""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
  <path fill="{palette["primary_container"]}" d="M4 12a4 4 0 0 1 4-4h12l5 5h15a4 4 0 0 1 4 4v20a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4z"/>
  <path fill="{palette["primary"]}" d="M4.5 18h39l-3.2 17.7a4 4 0 0 1-3.9 3.3H8.6a4 4 0 0 1-3.9-4.7z"/>
  <path fill="{palette["on_primary"]}" opacity=".12" d="M6.2 20h35.6l-.5 2.8H5.7z"/>
</svg>
'''


def render_text_icon(palette):
    """Recolor Papirus's text-file glyph with the current Matugen accent."""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
  <path fill="{palette["primary"]}" d="M2.75 1C2.33 1 2 1.333 2 1.75v12.5c0 .417.333.75.75.75h10.5c.418 0 .75-.333.75-.75V5.667L9.875 4.792 9 1z"/>
  <path fill="{palette["primary_container"]}" d="M9 1v4.167c0 .458.375.833.833.833H14z"/>
  <path fill="{palette["on_primary"]}" opacity=".68" d="M5 7h6v1H5zm0 2h6v1H5zm0 2h6v1H5zm0 2h3v1H5z"/>
</svg>
'''


def main():
    if len(sys.argv) < 2:
        raise SystemExit("usage: wallcolors.py IMAGE | --hue DEGREES dark|light SATURATION")
    mode = "dark"
    if sys.argv[1] == "--hue":
        hue = float(sys.argv[2]) % 360 / 360
        mode = "light" if len(sys.argv) >= 4 and sys.argv[3] == "light" else "dark"
        sat = max(0, min(1, float(sys.argv[4]) if len(sys.argv) > 4 else .5))
        chromatic = sat > .02
    else:
        wallpaper = Path(sys.argv[1])
        if not wallpaper.is_file():
            raise SystemExit(f"wallcolors: image not found: {wallpaper}")
        hue, sat, mean_l, chromatic = analyze(wallpaper)
    # Brightness never selects a light scheme.  Matugen's wallpaper-seeded
    # Material tonal palettes provide a perceptual, hue-preserving dark ramp.
    seed = tint(hue, sat, .45) if chromatic else "#787878"
    command = ["matugen", "color", "hex", seed, "-m", mode if sys.argv[1] == "--hue" else "dark", "-j", "hex"]
    if not chromatic:
        # Matugen's default tonal-spot scheme invents a blue-green hue for an
        # achromatic seed; its native monochrome scheme preserves grayscale.
        command.extend(["-t", "scheme-monochrome"])
    matugen = subprocess.run(command,
                             check=True, capture_output=True, text=True)
    generated = json.loads(matugen.stdout)
    material = generated["colors"]
    scheme = mode if sys.argv[1] == "--hue" else "dark"
    role = lambda name: material[name][scheme]["color"]
    surfaces = {"source_color": seed}
    if scheme == "dark":
        tones = generated["palettes"]["primary" if chromatic else "neutral"]
        tone = lambda value: tones[str(value)]["color"]
        surfaces.update(background=tone(5), surface=tone(10),
                         surface_container_lowest=tone(5), surface_container_low=tone(15),
                         surface_container=tone(20), surface_container_high=tone(25),
                         surface_container_highest=tone(30), surface_bright=tone(40),
                         outline_variant=tone(35), outline=tone(60))
    else:
        # Manual light mode remains opt-in; only wallpaper-driven dynamic mode
        # is subject to Sparrow's forced-dark policy.
        for name in ("background", "surface", "surface_container_lowest", "surface_container_low",
                     "surface_container", "surface_container_high", "surface_container_highest",
                     "surface_bright", "outline", "outline_variant"):
            surfaces[name] = role(name)
    for name in ("primary", "on_primary", "primary_container", "on_primary_container",
                 "secondary", "on_secondary", "secondary_container", "on_secondary_container",
                 "tertiary", "on_tertiary", "tertiary_container", "on_tertiary_container",
                 "error", "on_error", "on_surface", "on_background", "on_surface_variant"):
        surfaces[name] = role(name)
    if scheme == "dark" and not chromatic:
        # The Material monochrome scheme can inherit a default blue-green hue
        # when the source has no defined hue. Use its neutral tonal palette for
        # wallpaper UI roles instead of letting that fallback invent a color.
        surfaces.update(primary=tone(80), on_primary=tone(20), primary_container=tone(30),
                        on_primary_container=tone(90), secondary=tone(70), on_secondary=tone(20),
                        secondary_container=tone(30), on_secondary_container=tone(90),
                        tertiary=tone(70), on_tertiary=tone(20), tertiary_container=tone(30),
                        on_tertiary_container=tone(90), outline=tone(60), outline_variant=tone(35))
    surfaces.update(cream=surfaces["on_surface"], bright=surfaces["on_surface"],
                    subtle=surfaces["on_surface_variant"],
                    dim=tone(80) if scheme == "dark" else role("on_surface_variant"),
                    faint=tone(70) if scheme == "dark" else role("on_surface_variant"),
                    icon_dim=tone(90) if scheme == "dark" else role("on_surface"),
                    tick_rest=tone(80) if scheme == "dark" else role("on_surface_variant"))
    kitty = terminal_colors(surfaces)
    surfaces["terminal"] = kitty
    palette = json.dumps(surfaces, indent=2) + "\n"
    kdl = ("// Generated by Sparrow wallpaper palette; do not edit.\n"
           "layout {\n    border {\n"
           f'        active-color "{surfaces["primary"]}"\n'
           f'        inactive-color "{surfaces["outline_variant"]}"\n'
           "    }\n}\n")
    # The helper stages the whole Niri include tree and validates it before it
    # can replace the active generated fragment. Keep the JSON and Niri outputs
    # in step: on a failed Niri transaction, preserve the previous palette too.
    helper = Path(__file__).with_name("niri-config-transaction.py")
    request = json.dumps({"fragment": "generated-colors", "content": kdl}, ensure_ascii=False) + "\n"
    result = subprocess.run(
        [sys.executable, str(helper)], input=request, text=True,
        capture_output=True, check=False,
    )
    try:
        response = json.loads(result.stdout)
    except json.JSONDecodeError:
        response = {}
    if result.returncode != 0 or response.get("status") != "success":
        detail = response.get("message") or result.stderr.strip() or "Niri config transaction failed"
        raise RuntimeError(f"Niri colors were not applied: {detail}")

    atomic_write(CACHE / "palette.json", palette)
    config_home = Path(os.environ.get("XDG_CONFIG_HOME", HOME / ".config"))
    kitty_colors = config_home / "kitty" / "sparrow-colors.conf"
    try:
        colors_changed = atomic_write(kitty_colors, render_kitty(kitty))
    except OSError as exc:
        # Kitty is an optional consumer: it must never make wallpaper/palette
        # changes fail on systems without Kitty or a writable Kitty config dir.
        print(f"wallcolors: optional Kitty palette was not written: {exc}", file=sys.stderr)
    else:
        if colors_changed:
            # Kitty watches the top-level config paths, not files resolved by
            # globinclude. Its documented SIGUSR1 reload picks up this newly
            # written generated include in all currently running instances.
            try:
                subprocess.run(
                    ["pkill", "-USR1", "-x", "kitty"],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                    check=False,
                )
            except OSError as exc:
                print(f"wallcolors: Kitty palette was written, but live Kitty could not be reloaded: {exc}",
                      file=sys.stderr)

    data_home = Path(os.environ.get("XDG_DATA_HOME", HOME / ".local/share"))
    gtk_theme_dir = data_home / "themes" / "Sparrow" / "gtk-3.0"
    try:
        atomic_write(gtk_theme_dir / "gtk-dark.css", render_sparrow_gtk(surfaces))
    except (OSError, ValueError) as exc:
        print(f"wallcolors: optional Matugen GTK theme was not written: {exc}", file=sys.stderr)

    folder_icon = render_folder_icon(surfaces)
    icon_changes = False
    for icon_name in (
        "folder", "folder-open", "folder-documents", "folder-download",
        "folder-music", "folder-pictures", "folder-publicshare",
        "folder-templates", "folder-videos", "folder-remote",
        "folder-bookmarks", "folder-desktop", "user-desktop",
        "system-file-manager",
    ):
        try:
            icon_changes |= atomic_write(
                data_home / "icons" / "Sparrow" / "scalable" / "places" /
                f"{icon_name}.svg", folder_icon
            )
        except OSError as exc:
            print(f"wallcolors: optional GTK folder icon {icon_name} was not written: {exc}",
                  file=sys.stderr)
    try:
        icon_changes |= atomic_write(
            data_home / "icons" / "Sparrow" / "symbolic" / "places" /
            "folder-symbolic.svg", folder_icon
        )
    except OSError as exc:
        print(f"wallcolors: optional symbolic folder icon was not written: {exc}",
              file=sys.stderr)
    try:
        icon_changes |= atomic_write(
            data_home / "icons" / "Sparrow" / "scalable" / "mimetypes" /
            "text-x-generic.svg", render_text_icon(surfaces)
        )
    except OSError as exc:
        print(f"wallcolors: optional themed text icon was not written: {exc}",
              file=sys.stderr)
    if icon_changes:
        icon_root = data_home / "icons" / "Sparrow"
        try:
            subprocess.run(
                ["gtk-update-icon-cache", "--force", str(icon_root)],
                check=True, capture_output=True, text=True,
            )
        except (OSError, subprocess.CalledProcessError) as exc:
            print(f"wallcolors: Sparrow folder icons changed, but the icon cache could not be refreshed: {exc}",
                  file=sys.stderr)


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, subprocess.SubprocessError) as exc:
        print(f"wallcolors: {exc}", file=sys.stderr)
        raise SystemExit(1)
